package eu.asyncro.passmatters.config.paste.view;

import eu.asyncro.passmatters.config.paste.controller.PasteOptionConfigurator;
import eu.asyncro.passmatters.main.view.BaseFrame;

/**
 * This frame is shown when paste option validation wasn't successful.
 * @author Milan
 */
public class PasteValidationFailedFrame extends BaseFrame {

    private final PasteOptionConfigurator configurator;
    
    /**
     * Creates new form PasteOptionValidationFailedDialog
     * @param configurator
     */
    public PasteValidationFailedFrame(PasteOptionConfigurator configurator) {
        super();
        this.configurator = configurator;
        initComponents();
        showFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblValidationFailed = new javax.swing.JLabel();
        lblTryAgain = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnTryAgain = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Validation Failed");

        lblValidationFailed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValidationFailed.setText("Unfortunatelly, paste option validation failed.");
        lblValidationFailed.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblTryAgain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTryAgain.setText("It is recommended that you try again.");

        btnExit.setText("Exit");
        btnExit.setFocusable(false);
        btnExit.setName("btnExit"); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnTryAgain.setText("Try again");
        btnTryAgain.setName("btnTryAgain"); // NOI18N
        btnTryAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTryAgainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValidationFailed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTryAgain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTryAgain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblValidationFailed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTryAgain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnTryAgain))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnTryAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTryAgainActionPerformed
        dispose();
        configurator.configurePasteOption();
    }//GEN-LAST:event_btnTryAgainActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnTryAgain;
    private javax.swing.JLabel lblTryAgain;
    private javax.swing.JLabel lblValidationFailed;
    // End of variables declaration//GEN-END:variables
}
